version = 0.1
[default.global.parameters]
stack_name = "moving-crew-ai"
region = "us-east-1"
confirm_changeset = false
resolve_s3 = true
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"rahul-dev\""
s3_prefix = "moving-crew-ai-rahul"
disable_rollback = false
stack_name = "moving-crew-ai-rahul"
resolve_image_repos = true