AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: rahul-dev
    Description: Environment name

Resources:
  CrewApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-async-crew-api"
      CodeUri: src/api/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          JOBS_TABLE: rahul-dev-crew-jobs
      Policies:
        - DynamoDBCrudPolicy:
            TableName: rahul-dev-crew-jobs
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource: !GetAtt CrewProcessorFunction.Arn
      Events:
        QueryApi:
          Type: Api
          Properties:
            Path: /query
            Method: POST
        StatusApi:
          Type: Api
          Properties:
            Path: /status/{job_id}
            Method: GET

  CrewProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-async-crew-processor"
      CodeUri: src/processor/
      Handler: processor.lambda_handler
      Runtime: python3.11
      Timeout: 900
      Environment:
        Variables:
          JOBS_TABLE: rahul-dev-crew-jobs
      Policies:
        - DynamoDBCrudPolicy:
            TableName: rahul-dev-crew-jobs

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Description: API Gateway endpoint URL
