AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: rahul-dev

Resources:
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Environment}-crew-jobs"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  CrewApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-moving-crew-api"
      CodeUri: src/api/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          JOBS_TABLE: !Ref JobsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource: !GetAtt CrewProcessorFunction.Arn
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  CrewProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Environment}-moving-crew-processor"
      CodeUri: src/processor/
      Handler: processor.lambda_handler
      Runtime: python3.11
      Timeout: 900
      Environment:
        Variables:
          JOBS_TABLE: !Ref JobsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
